<?php /*
<footer>
  <div id='social'>
    <a href='https://secure.actblue.com/contribute/page/lets-go-bernie?refcode=heroku_events' class='contribute' target='_blank'>Contribute to the Campaign</a>
    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://map.berniesanders.com" data-text="Join the July 29 @BernieSanders organizing kick-off! Find nearby events and #FeelTheBern @BernieMeetups" data-related="BernieSanders">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      <div class="fb-share-button" data-href="http://map.berniesanders.com" data-layout="button_count"></div>
  <div class="fb-share-button" data-href="http://map.berniesanders.com" data-layout="button_count"></div>
  </div>
  <sub style='color: #999999; text-align: center;' >
    &reg; <a href='http://www.berniesanders.com' target='_blank'>Benrie Sanders</a></sub>
</footer>
 */ ?>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64649524-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
